### ISSUE TITLE
Issue in Multi Website admin shopping cart

### ISSUE THREAD

**Issue by subineseller** [redchamps/customer-shopping-carts-tab-fix#1]
Hi

we are developing a multi website
I am facing issues in the store 2 , that the customer shopping cart item is not showing in admin after installing this module.
added two items in cart https://prnt.sc/td9gza
in backend its showing 0 records found  https://prnt.sc/td9hn2
store 1 is fine now.
Magento ver. 2.3.5-p1
How can we fix this.

Thanks

**Comment by rav-redchamps** [comment]
@subineseller We hope you mean 2 websites instead of 2 stores. We are trying to repeat the problem at our side & get back to you shortly.

**Comment by subineseller** [comment]
https://prnt.sc/tdahlg
Muti website
![image](https://user-images.githubusercontent.com/60872206/86764968-2947f400-c066-11ea-80ee-47c68c1c6be2.png)
In db its showing item count as 3 for store_id 2 (quote table)
0 in admin

**Comment by rav-redchamps** [comment]
Thanks, @subineseller. We are able to repeat it &  the fix will be released shortly.

**Comment by subineseller** [comment]
Thanks,waiting for the update :)

**Comment by rav-redchamps** [comment]
Done ✅  Please try upgrading to version 1.1.0 & let me know if this solves the problem.

**Comment by subineseller** [comment]
Thanks for the quick fix.
Its working fine now.
